name: slivers_uploader
description: A file upload tool, which can be used for slicing large files.

version: 0.0.4

repository: https://github.com/jacklee1995/Slivers-Uploader
homepage: https://github.com/jacklee1995/Slivers-Uploader
auth:
  name: Jcak Lee
  email: 291148484@163.com
  home: http://thispage.tech

licence: MIT


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
